### ISSUE TITLE
[q] Perhaps rename?

### ISSUE THREAD

**Issue by xplshn** [FigSystems/IcePak#9]
Hi, I develop these projects: https://github.com/xplshn/pelf & https://github.com/xplshn/AppBundleHUB
Perhaps it'd be best to rename in order to avoid confusion?
Also, I'm very much interested in the overlay* stuff you have going on here, I'd like to hear your thoughts on https://github.com/xplshn/pelf/blob/pelf-ng/pelfCreator, and more specifically, on the "`proto`" mode, which is this AppRun right here: https://github.com/xplshn/pelf/blob/pelf-ng/assets/AppRun.sharun.ovfsProto

(proto mode means: If a directory named proto is found on the AppDir, we overlay it over the user's `/`, so that the program works without having to run any patches, we use bwrap to run it when we use the proto mode)

NOTE: I've no problems with you using code from my repo, that's perfectly fine, just __consider__ changing the name of your project, please :)
Or helping me out with my existing efforts :)

**Comment by dleggo** [comment]
Hi @xplshn ,
Sorry about the naming issue! I had no intent to plagerise anything. I renamed this to **IcePak**.

> Also, I'm very much interested in the overlay* stuff you have going on here, I'd like to hear your thoughts on https://github.com/xplshn/pelf/blob/pelf-ng/pelfCreator, and more specifically, on the "proto" mode, which is this AppRun right here: https://github.com/xplshn/pelf/blob/pelf-ng/assets/AppRun.sharun.ovfsProto

I looked at **pElf** briefly, before reviewing the necessity of starting this project, and I have to admit that I didn't look into it enough because of the name. Imho pElf just sounded like a souped up static linker. 🤣 Looking at it now though, it looks like you have a nice setup with that though! My one suggestion thoughb is that fuse has been found to be much slower then a normal mount, and as such should maybe be avoided? Bubblewrap 0.11.0 has an `--overlay` option which utilizes user namespaces and kernel mounting which will have much better performance.

**Comment by xplshn** [comment]
PELF (Pack an ELF) can have multiple editions, we used to have a GZIP one and a Squashfs one, it'd be great if we could get them to work without FUSE, but I'm not sure how we could:
1. Avoid FUSE
2. Not read the entire archive or extract it into /tmp, etc

**Comment by xplshn** [comment]
Thanks for renaming by the way
